### ISSUE TITLE
Markers behaving strangely when pinching on ios.

### ISSUE THREAD

**Issue by supermarpe** [kartena/Proj4Leaflet#85]
When zooming the map on an ios device (by using two finger pinch) the markers/pins resets to standard zoom until the pinch is done, and then the markers/pins is set to correct position again.

**Comment by perliedman** [comment]
Sounds a bit like the problem that was (at least partially) solved by #73. What version of Proj4Leaflet are you running?

Ideally, if you could provide jsfiddle or similar to see the problem live, that would be great.

**Comment by supermarpe** [comment]
I've downloaded the latest version, but I still experience the same problem.

Will try to get a jsfiddle-example up.

**Comment by perliedman** [comment]
Closing since no new information has showed up in a long time.
